### ISSUE TITLE
IE8 styles issue

### ISSUE THREAD

**Issue by dgfischer** [erikzaadi/jQueryPlugins#3]
I am using version 1.0 of printElement.  Works great for forms now!!

In IE8 (not sure about IE7 since testing has been only done in 8) when you attempt to print a form that has styles, the styles are dropped when printed (things like a jqueryui theme).  After some testing and looking around, it appears that the issue is in the _getBaseHref().  After I modified it to be the following, it printed just fine.  It appears that FF does not use this property or uses it differently from IE, but this fixed it.

function _getBaseHref() {
        return window.location.protocol + "//" + window.location.hostname + (window.location.port ? ":" + window.location.port : "") + window.location.pathname;
    }

**Comment by erikzaadi** [comment]
Thanks dgfisher.. 
I'll run some test with all browsers again with your fix, then add it to the master.. 

Glad you liked the plugin..

Erik

**Comment by erikzaadi** [comment]
Added, thanks (See version 1.1)
