### ISSUE TITLE
error: printElment is not a function 

### ISSUE THREAD

**Issue by mahbube** [erikzaadi/jQueryPlugins#39]
when i use this in a local server , it work correctly, but after uploadin it , this function dont work. 
the error is :
1) syntax error in jquery.printElment.min.js

2) $(''#mydiv').printElment is not a function

what shoud i do?

**Comment by ghost** [comment]
Missing a e? 
You should write

```
    $("#mydiv").printElement 
```
1. printElement with e
2. #mydiv embedded in doublequotes (=") 

;)

**Comment by mahbube** [comment]
thanks, actually I wrote it by a correct dictation, but I should use a directe address for src attribiute in script tag.any way, I solve it. thanks 4 ur attention.
