### ISSUE TITLE
PrintElement not working correctly with Safari 4 and urls with ports

### ISSUE THREAD

**Issue by tschofen** [erikzaadi/jQueryPlugins#4]
The base that is set in the iFrames head doesn't work correctly with Safari 4 and with port numbers:

Here's how I solved it:
    function _getBaseHref(){
            var port =  (window.location.port) ? ':'+  + window.location.port : '';
        return window.location.protocol +'//'+ window.location.hostname + (port) + window.location.pathname;
    }

**Comment by erikzaadi** [comment]
Thanks!

**Comment by bgreater** [comment]
This issues affected IE 6 - 8 in XP.  Worked in Vista however.  I fixed the same way before finding this post.

**Comment by erikzaadi** [comment]
Added, thanks (see version 1.1)
