### ISSUE TITLE
Loading Additional CSS File fails when host in running on different port

### ISSUE THREAD

**Issue by palamccc** [erikzaadi/jQueryPlugins#6]
When i am running my webserver on port 8080 instead of 80, (overrideElementCSS) CSS files are not loaded properly.

The reason in function _getBaseHref  don't use location.port  while creating base href.
function _getBaseHref(){
        return window.location.protocol + window.location.hostname + window.location.pathname;
}

**Comment by erikzaadi** [comment]
Fixed in version 1.1
